### ISSUE TITLE
Make searchForPhrase independent of Jisho API

### ISSUE THREAD

**Issue by Nonemoticoner** [mistval/unofficial-jisho-api#2]
I suggest to drop being dependent upon Jisho API for word search. Two reasons:

1. Official Jisho API does not provide all the data in its word/phrase endpoint e.g. information about JLPT level is missing. 
2. `searchForPhrase` method is just routing data from Jisho API and anyone could make a simple fetch call. So its usefulness in current version is a bit questionable.

Btw. very useful repo ;)

**Comment by mistval** [comment]
Hi, thanks for your suggestion. So you suggest scraping jisho.org for word data, instead of using the API?

You're right that the site has data that the API does not have, and it would be nice to have that data. (I'd like to get the JLPT level for my purposes too) On the other hand, the API has some data that the search results overview doesn't, although that data is somewhat less important (for example links to external sources).

I'm of the opinion though that if there's data in the API, we should use the API to get it, since using the API is officially supported, less prone to bugs, won't break when Jisho's page format changes, and is simpler to maintain on my end (effortless, really), compared to scraping. It's true that simply providing a method that calls the API doesn't really save anyone very much effort, but it is cohesive with the aims of the package, and doesn't hurt.

I was thinking a good solution here would be to add a boolean argument to the searchForWord function. The function would always call the API, and in addition, if the boolean argument were true, it would scrape the JLPT data and such from the Jisho website and add that to the results from the API. However it seems that the Jisho website and the API actually return different results, so that would complicate trying to merge that data.

I'll keep this suggestion in mind. Due to different priorities, I'm unlikely to do anything about it anytime soon, but I'd like to do something about it eventually. I'd also be happy to accept a PR that adds either a function to scrape the website, or a boolean argument to the searchForWord function like I mentioned above.

**Comment by mistval** [comment]
New version 1.2.0 has a scrapeForPhrase function that scrapes most of the information off of the word/phrase page. You can get JLPT tags and other information by using that. Please see the updated README for more info.

Implemented in a0dad0552edc30d5fab78d1917f3bf09c9996f22

Closing, feel free to comment or open another issue if it's missing some data that you would like me to try to add.
