### ISSUE TITLE
Attempting to import this project into my React Native Project

### ISSUE THREAD

**Issue by Louis345** [mistval/unofficial-jisho-api#5]
I do not know what details to provide, but I am having an extremely hard time importing the project in my App. I went through the normally NPM install unofficial-jisho-api. Attempted to import the project by typing in ``` import jisho from 'unofficial-jisho-api';``` 

My project fails each and every time.  I deleted the node modules and then did an npm install and still did not resolve my issue.  Any help will be greatly appreciated.

**Comment by mistval** [comment]
Hi, I'm unfamiliar with React Native, but I'll try to help if I can. Can you tell me specifically how it fails? Does NPM give error messages? If not, what is the value of the **jisho** variable after you import, and what about it isn't working?

If all else fails, you could always try just using the https://github.com/mistval/unofficial-jisho-api/blob/master/index.js file in your project instead of installing the module with NPM. But let's try making it work with NPM first.

**Comment by Louis345** [comment]
I think I will try to import the file into my project.  As far as debugging is concerned, I am not able to get to the point of seeing where it fails, because as soon as I try to import the project it fails. It's like webpack cannot import it correctly.  Another odd issue is that vscode my editor is not detecting the project, but if I right click on the import statement it takes to the module. I am really unsure on how to troubleshoot this issue. My knowledge is really limited here. But I do thank you for such an awesome proejct.

**Comment by Louis345** [comment]
It's because React Native package manager is having trouble with require. It has nothing to do with your code.

**Comment by mistval** [comment]
Gotcha, I'll close this issue then, feel free to reopen if you need any further assistance.
